require "user.plugins.packer"
require "user.plugins.statusline"
require "user.plugins.theme"
require "user.plugins.bufferline"
require "user.plugins.filetree"
require "user.plugins.telescope"
require "user.plugins.cmp"
